/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface DownloadRequest {
  /** Instagram post/reel/story URL */
  url: string;
}

/**
 * Type of media
 */
export type MediaItemType = typeof MediaItemType[keyof typeof MediaItemType];


export const MediaItemType = {
  video: 'video',
  image: 'image',
} as const;

export interface MediaItem {
  /** Direct download URL for the media */
  url: string;
  /** Type of media */
  type: MediaItemType;
  /** Quality label (e.g. HD, SD) */
  quality: string;
}

/**
 * Instagram media type
 */
export type DownloadResponseMediaType = typeof DownloadResponseMediaType[keyof typeof DownloadResponseMediaType];


export const DownloadResponseMediaType = {
  reel: 'reel',
  video: 'video',
  photo: 'photo',
  story: 'story',
  carousel: 'carousel',
} as const;

export interface DownloadResponse {
  success: boolean;
  /** Post title or caption (if available) */
  title?: string;
  /** Thumbnail/preview image URL */
  thumbnail?: string;
  /** Instagram media type */
  mediaType: DownloadResponseMediaType;
  /** List of downloadable media items (multiple for carousels) */
  items: MediaItem[];
}

export interface ErrorResponse {
  success: boolean;
  error: string;
}

