/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * Accepts an Instagram URL and returns media metadata including thumbnail, title, and download links
 * @summary Fetch Instagram media metadata
 */
export const FetchInstagramMediaBody = zod.object({
  "url": zod.string().describe('Instagram post\/reel\/story URL')
})

export const FetchInstagramMediaResponse = zod.object({
  "success": zod.boolean(),
  "title": zod.string().optional().describe('Post title or caption (if available)'),
  "thumbnail": zod.string().optional().describe('Thumbnail\/preview image URL'),
  "mediaType": zod.enum(['reel', 'video', 'photo', 'story', 'carousel']).describe('Instagram media type'),
  "items": zod.array(zod.object({
  "url": zod.string().describe('Direct download URL for the media'),
  "type": zod.enum(['video', 'image']).describe('Type of media'),
  "quality": zod.string().describe('Quality label (e.g. HD, SD)')
})).describe('List of downloadable media items (multiple for carousels)')
})


