/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

/**
 * Instagram media type
 */
export type DownloadResponseMediaType = typeof DownloadResponseMediaType[keyof typeof DownloadResponseMediaType];


export const DownloadResponseMediaType = {
  reel: 'reel',
  video: 'video',
  photo: 'photo',
  story: 'story',
  carousel: 'carousel',
} as const;
