/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { DownloadResponseMediaType } from './downloadResponseMediaType';
import type { MediaItem } from './mediaItem';

export interface DownloadResponse {
  success: boolean;
  /** Post title or caption (if available) */
  title?: string;
  /** Thumbnail/preview image URL */
  thumbnail?: string;
  /** Instagram media type */
  mediaType: DownloadResponseMediaType;
  /** List of downloadable media items (multiple for carousels) */
  items: MediaItem[];
}
