/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { MediaItemType } from './mediaItemType';

export interface MediaItem {
  /** Direct download URL for the media */
  url: string;
  /** Type of media */
  type: MediaItemType;
  /** Quality label (e.g. HD, SD) */
  quality: string;
}
